### ISSUE TITLE
payload down 

### ISSUE THREAD

**Issue by Devjam81** [xerub/ibex#1]
Hello can you help us to have success payload , offset is not how this please inform thanks
![espace de travail 1_001](https://cloud.githubusercontent.com/assets/5838238/8083338/22e73654-0f84-11e5-8aa8-9d6d78384046.png)

**Comment by xerub** [comment]
Judging from that picture, you just need to give "go" commands to the payload: "go read addr size" or "go blobs". Not exactly sure what are you trying to achieve.
