### ISSUE TITLE
Memory image not valid

### ISSUE THREAD

**Issue by b00tsn0w** [xerub/ibex#2]
![capture du 2015-06-15 21 59 11](https://cloud.githubusercontent.com/assets/7189725/8169448/eb7a19aa-13a9-11e5-872f-f9bd81c75616.png)
I have this problem !

**Comment by b00tsn0w** [comment]
I have an iPad2,4

**Comment by xerub** [comment]
The iBoot on your device is not pwned, so the payload doesn't work correctly.
